// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoWfqoGjY6WVRIKesnSNuGG0WrGK-7xYA',
    appId: '1:156934326166:web:cfd311519516060b243fb7',
    messagingSenderId: '156934326166',
    projectId: 'bugoff-76873',
    authDomain: 'bugoff-76873.firebaseapp.com',
    storageBucket: 'bugoff-76873.appspot.com',
    measurementId: 'G-LRFJB48HBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAusi9siJ5nluqQzcXSpfysA0NlM-2qcw',
    appId: '1:156934326166:android:06d11460f7a67c86243fb7',
    messagingSenderId: '156934326166',
    projectId: 'bugoff-76873',
    storageBucket: 'bugoff-76873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJ3sS192DkKUBEOxePbd3T3Hv6oo_AgA',
    appId: '1:156934326166:ios:8af5f43507372e5a243fb7',
    messagingSenderId: '156934326166',
    projectId: 'bugoff-76873',
    storageBucket: 'bugoff-76873.appspot.com',
    iosClientId: '156934326166-uvgotkp5bf75690fqqurh3mr9d9b9jfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.engageFiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJ3sS192DkKUBEOxePbd3T3Hv6oo_AgA',
    appId: '1:156934326166:ios:8af5f43507372e5a243fb7',
    messagingSenderId: '156934326166',
    projectId: 'bugoff-76873',
    storageBucket: 'bugoff-76873.appspot.com',
    iosClientId: '156934326166-uvgotkp5bf75690fqqurh3mr9d9b9jfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.engageFiles',
  );
}
